#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portakal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AirHotelCar")]
	public partial class AirDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHavalimanlari(Havalimanlari instance);
    partial void UpdateHavalimanlari(Havalimanlari instance);
    partial void DeleteHavalimanlari(Havalimanlari instance);
    partial void InsertHavayollari(Havayollari instance);
    partial void UpdateHavayollari(Havayollari instance);
    partial void DeleteHavayollari(Havayollari instance);
    partial void InsertMusteriler(Musteriler instance);
    partial void UpdateMusteriler(Musteriler instance);
    partial void DeleteMusteriler(Musteriler instance);
    partial void InsertSehirler(Sehirler instance);
    partial void UpdateSehirler(Sehirler instance);
    partial void DeleteSehirler(Sehirler instance);
    partial void InsertUcaklar(Ucaklar instance);
    partial void UpdateUcaklar(Ucaklar instance);
    partial void DeleteUcaklar(Ucaklar instance);
    partial void InsertUcuslar(Ucuslar instance);
    partial void UpdateUcuslar(Ucuslar instance);
    partial void DeleteUcuslar(Ucuslar instance);
    partial void InsertUlkeler(Ulkeler instance);
    partial void UpdateUlkeler(Ulkeler instance);
    partial void DeleteUlkeler(Ulkeler instance);
    partial void InsertModeller(Modeller instance);
    partial void UpdateModeller(Modeller instance);
    partial void DeleteModeller(Modeller instance);
    partial void InsertSatisHareketleri(SatisHareketleri instance);
    partial void UpdateSatisHareketleri(SatisHareketleri instance);
    partial void DeleteSatisHareketleri(SatisHareketleri instance);
    #endregion
		
		public AirDataContext() : 
				base(global::Portakal.Properties.Settings.Default.AirHotelCarConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AirDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AirDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AirDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AirDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Havalimanlari> Havalimanlaris
		{
			get
			{
				return this.GetTable<Havalimanlari>();
			}
		}
		
		public System.Data.Linq.Table<Havayollari> Havayollaris
		{
			get
			{
				return this.GetTable<Havayollari>();
			}
		}
		
		public System.Data.Linq.Table<Musteriler> Musterilers
		{
			get
			{
				return this.GetTable<Musteriler>();
			}
		}
		
		public System.Data.Linq.Table<Sehirler> Sehirlers
		{
			get
			{
				return this.GetTable<Sehirler>();
			}
		}
		
		public System.Data.Linq.Table<Ucaklar> Ucaklars
		{
			get
			{
				return this.GetTable<Ucaklar>();
			}
		}
		
		public System.Data.Linq.Table<Ucuslar> Ucuslars
		{
			get
			{
				return this.GetTable<Ucuslar>();
			}
		}
		
		public System.Data.Linq.Table<Ulkeler> Ulkelers
		{
			get
			{
				return this.GetTable<Ulkeler>();
			}
		}
		
		public System.Data.Linq.Table<Modeller> Modellers
		{
			get
			{
				return this.GetTable<Modeller>();
			}
		}
		
		public System.Data.Linq.Table<SatisHareketleri> SatisHareketleris
		{
			get
			{
				return this.GetTable<SatisHareketleri>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Havalimanlari")]
	public partial class Havalimanlari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HavalimaniID;
		
		private string _HavalimaniAdi;
		
		private string _Kisaltmasi;
		
		private int _SehirID;
		
		private string _Aciklama;
		
		private bool _Silindi;
		
		private EntitySet<Ucuslar> _Ucuslars;
		
		private EntitySet<Ucuslar> _Ucuslars1;
		
		private EntitySet<Ucuslar> _Ucuslars2;
		
		private EntityRef<Sehirler> _Sehirler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHavalimaniIDChanging(int value);
    partial void OnHavalimaniIDChanged();
    partial void OnHavalimaniAdiChanging(string value);
    partial void OnHavalimaniAdiChanged();
    partial void OnKisaltmasiChanging(string value);
    partial void OnKisaltmasiChanged();
    partial void OnSehirIDChanging(int value);
    partial void OnSehirIDChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    #endregion
		
		public Havalimanlari()
		{
			this._Ucuslars = new EntitySet<Ucuslar>(new Action<Ucuslar>(this.attach_Ucuslars), new Action<Ucuslar>(this.detach_Ucuslars));
			this._Ucuslars1 = new EntitySet<Ucuslar>(new Action<Ucuslar>(this.attach_Ucuslars1), new Action<Ucuslar>(this.detach_Ucuslars1));
			this._Ucuslars2 = new EntitySet<Ucuslar>(new Action<Ucuslar>(this.attach_Ucuslars2), new Action<Ucuslar>(this.detach_Ucuslars2));
			this._Sehirler = default(EntityRef<Sehirler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HavalimaniID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HavalimaniID
		{
			get
			{
				return this._HavalimaniID;
			}
			set
			{
				if ((this._HavalimaniID != value))
				{
					this.OnHavalimaniIDChanging(value);
					this.SendPropertyChanging();
					this._HavalimaniID = value;
					this.SendPropertyChanged("HavalimaniID");
					this.OnHavalimaniIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HavalimaniAdi", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string HavalimaniAdi
		{
			get
			{
				return this._HavalimaniAdi;
			}
			set
			{
				if ((this._HavalimaniAdi != value))
				{
					this.OnHavalimaniAdiChanging(value);
					this.SendPropertyChanging();
					this._HavalimaniAdi = value;
					this.SendPropertyChanged("HavalimaniAdi");
					this.OnHavalimaniAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kisaltmasi", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Kisaltmasi
		{
			get
			{
				return this._Kisaltmasi;
			}
			set
			{
				if ((this._Kisaltmasi != value))
				{
					this.OnKisaltmasiChanging(value);
					this.SendPropertyChanging();
					this._Kisaltmasi = value;
					this.SendPropertyChanged("Kisaltmasi");
					this.OnKisaltmasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SehirID", DbType="Int NOT NULL")]
		public int SehirID
		{
			get
			{
				return this._SehirID;
			}
			set
			{
				if ((this._SehirID != value))
				{
					if (this._Sehirler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSehirIDChanging(value);
					this.SendPropertyChanging();
					this._SehirID = value;
					this.SendPropertyChanged("SehirID");
					this.OnSehirIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Havalimanlari_Ucuslar", Storage="_Ucuslars", ThisKey="HavalimaniID", OtherKey="KalkisYeriID")]
		public EntitySet<Ucuslar> Ucuslars
		{
			get
			{
				return this._Ucuslars;
			}
			set
			{
				this._Ucuslars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Havalimanlari_Ucuslar1", Storage="_Ucuslars1", ThisKey="HavalimaniID", OtherKey="InisYeriID")]
		public EntitySet<Ucuslar> Ucuslars1
		{
			get
			{
				return this._Ucuslars1;
			}
			set
			{
				this._Ucuslars1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Havalimanlari_Ucuslar2", Storage="_Ucuslars2", ThisKey="HavalimaniID", OtherKey="KalkisYeriID")]
		public EntitySet<Ucuslar> Ucuslars2
		{
			get
			{
				return this._Ucuslars2;
			}
			set
			{
				this._Ucuslars2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sehirler_Havalimanlari", Storage="_Sehirler", ThisKey="SehirID", OtherKey="SehirID", IsForeignKey=true)]
		public Sehirler Sehirler
		{
			get
			{
				return this._Sehirler.Entity;
			}
			set
			{
				Sehirler previousValue = this._Sehirler.Entity;
				if (((previousValue != value) 
							|| (this._Sehirler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sehirler.Entity = null;
						previousValue.Havalimanlaris.Remove(this);
					}
					this._Sehirler.Entity = value;
					if ((value != null))
					{
						value.Havalimanlaris.Add(this);
						this._SehirID = value.SehirID;
					}
					else
					{
						this._SehirID = default(int);
					}
					this.SendPropertyChanged("Sehirler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ucuslars(Ucuslar entity)
		{
			this.SendPropertyChanging();
			entity.Havalimanlari = this;
		}
		
		private void detach_Ucuslars(Ucuslar entity)
		{
			this.SendPropertyChanging();
			entity.Havalimanlari = null;
		}
		
		private void attach_Ucuslars1(Ucuslar entity)
		{
			this.SendPropertyChanging();
			entity.Havalimanlari1 = this;
		}
		
		private void detach_Ucuslars1(Ucuslar entity)
		{
			this.SendPropertyChanging();
			entity.Havalimanlari1 = null;
		}
		
		private void attach_Ucuslars2(Ucuslar entity)
		{
			this.SendPropertyChanging();
			entity.Havalimanlari2 = this;
		}
		
		private void detach_Ucuslars2(Ucuslar entity)
		{
			this.SendPropertyChanging();
			entity.Havalimanlari2 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Havayollari")]
	public partial class Havayollari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HavayoluID;
		
		private string _HavayoluAdi;
		
		private int _UlkeID;
		
		private int _FotografID;
		
		private string _Aciklama;
		
		private bool _Silindi;
		
		private string _Kisaltmasi;
		
		private EntitySet<Ucaklar> _Ucaklars;
		
		private EntityRef<Ulkeler> _Ulkeler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHavayoluIDChanging(int value);
    partial void OnHavayoluIDChanged();
    partial void OnHavayoluAdiChanging(string value);
    partial void OnHavayoluAdiChanged();
    partial void OnUlkeIDChanging(int value);
    partial void OnUlkeIDChanged();
    partial void OnFotografIDChanging(int value);
    partial void OnFotografIDChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    partial void OnKisaltmasiChanging(string value);
    partial void OnKisaltmasiChanged();
    #endregion
		
		public Havayollari()
		{
			this._Ucaklars = new EntitySet<Ucaklar>(new Action<Ucaklar>(this.attach_Ucaklars), new Action<Ucaklar>(this.detach_Ucaklars));
			this._Ulkeler = default(EntityRef<Ulkeler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HavayoluID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HavayoluID
		{
			get
			{
				return this._HavayoluID;
			}
			set
			{
				if ((this._HavayoluID != value))
				{
					this.OnHavayoluIDChanging(value);
					this.SendPropertyChanging();
					this._HavayoluID = value;
					this.SendPropertyChanged("HavayoluID");
					this.OnHavayoluIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HavayoluAdi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string HavayoluAdi
		{
			get
			{
				return this._HavayoluAdi;
			}
			set
			{
				if ((this._HavayoluAdi != value))
				{
					this.OnHavayoluAdiChanging(value);
					this.SendPropertyChanging();
					this._HavayoluAdi = value;
					this.SendPropertyChanged("HavayoluAdi");
					this.OnHavayoluAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UlkeID", DbType="Int NOT NULL")]
		public int UlkeID
		{
			get
			{
				return this._UlkeID;
			}
			set
			{
				if ((this._UlkeID != value))
				{
					if (this._Ulkeler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUlkeIDChanging(value);
					this.SendPropertyChanging();
					this._UlkeID = value;
					this.SendPropertyChanged("UlkeID");
					this.OnUlkeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotografID", DbType="Int NOT NULL")]
		public int FotografID
		{
			get
			{
				return this._FotografID;
			}
			set
			{
				if ((this._FotografID != value))
				{
					this.OnFotografIDChanging(value);
					this.SendPropertyChanging();
					this._FotografID = value;
					this.SendPropertyChanged("FotografID");
					this.OnFotografIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(50)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kisaltmasi", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Kisaltmasi
		{
			get
			{
				return this._Kisaltmasi;
			}
			set
			{
				if ((this._Kisaltmasi != value))
				{
					this.OnKisaltmasiChanging(value);
					this.SendPropertyChanging();
					this._Kisaltmasi = value;
					this.SendPropertyChanged("Kisaltmasi");
					this.OnKisaltmasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Havayollari_Ucaklar", Storage="_Ucaklars", ThisKey="HavayoluID", OtherKey="HavayollariID")]
		public EntitySet<Ucaklar> Ucaklars
		{
			get
			{
				return this._Ucaklars;
			}
			set
			{
				this._Ucaklars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ulkeler_Havayollari", Storage="_Ulkeler", ThisKey="UlkeID", OtherKey="UlkeID", IsForeignKey=true)]
		public Ulkeler Ulkeler
		{
			get
			{
				return this._Ulkeler.Entity;
			}
			set
			{
				Ulkeler previousValue = this._Ulkeler.Entity;
				if (((previousValue != value) 
							|| (this._Ulkeler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ulkeler.Entity = null;
						previousValue.Havayollaris.Remove(this);
					}
					this._Ulkeler.Entity = value;
					if ((value != null))
					{
						value.Havayollaris.Add(this);
						this._UlkeID = value.UlkeID;
					}
					else
					{
						this._UlkeID = default(int);
					}
					this.SendPropertyChanged("Ulkeler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ucaklars(Ucaklar entity)
		{
			this.SendPropertyChanging();
			entity.Havayollari = this;
		}
		
		private void detach_Ucaklars(Ucaklar entity)
		{
			this.SendPropertyChanging();
			entity.Havayollari = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Musteriler")]
	public partial class Musteriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MusteriID;
		
		private string _MusteriAdi;
		
		private string _MusteriSoyadi;
		
		private string _EvTelefonu;
		
		private string _CepTelefonu;
		
		private string _Adres;
		
		private int _SehirID;
		
		private string _Aciklama;
		
		private bool _Silindi;
		
		private string _TCKimlikNo;
		
		private EntitySet<SatisHareketleri> _SatisHareketleris;
		
		private EntityRef<Sehirler> _Sehirler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMusteriIDChanging(int value);
    partial void OnMusteriIDChanged();
    partial void OnMusteriAdiChanging(string value);
    partial void OnMusteriAdiChanged();
    partial void OnMusteriSoyadiChanging(string value);
    partial void OnMusteriSoyadiChanged();
    partial void OnEvTelefonuChanging(string value);
    partial void OnEvTelefonuChanged();
    partial void OnCepTelefonuChanging(string value);
    partial void OnCepTelefonuChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnSehirIDChanging(int value);
    partial void OnSehirIDChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    partial void OnTCKimlikNoChanging(string value);
    partial void OnTCKimlikNoChanged();
    #endregion
		
		public Musteriler()
		{
			this._SatisHareketleris = new EntitySet<SatisHareketleri>(new Action<SatisHareketleri>(this.attach_SatisHareketleris), new Action<SatisHareketleri>(this.detach_SatisHareketleris));
			this._Sehirler = default(EntityRef<Sehirler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MusteriID
		{
			get
			{
				return this._MusteriID;
			}
			set
			{
				if ((this._MusteriID != value))
				{
					this.OnMusteriIDChanging(value);
					this.SendPropertyChanging();
					this._MusteriID = value;
					this.SendPropertyChanged("MusteriID");
					this.OnMusteriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriAdi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MusteriAdi
		{
			get
			{
				return this._MusteriAdi;
			}
			set
			{
				if ((this._MusteriAdi != value))
				{
					this.OnMusteriAdiChanging(value);
					this.SendPropertyChanging();
					this._MusteriAdi = value;
					this.SendPropertyChanged("MusteriAdi");
					this.OnMusteriAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriSoyadi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MusteriSoyadi
		{
			get
			{
				return this._MusteriSoyadi;
			}
			set
			{
				if ((this._MusteriSoyadi != value))
				{
					this.OnMusteriSoyadiChanging(value);
					this.SendPropertyChanging();
					this._MusteriSoyadi = value;
					this.SendPropertyChanged("MusteriSoyadi");
					this.OnMusteriSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvTelefonu", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string EvTelefonu
		{
			get
			{
				return this._EvTelefonu;
			}
			set
			{
				if ((this._EvTelefonu != value))
				{
					this.OnEvTelefonuChanging(value);
					this.SendPropertyChanging();
					this._EvTelefonu = value;
					this.SendPropertyChanged("EvTelefonu");
					this.OnEvTelefonuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CepTelefonu", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CepTelefonu
		{
			get
			{
				return this._CepTelefonu;
			}
			set
			{
				if ((this._CepTelefonu != value))
				{
					this.OnCepTelefonuChanging(value);
					this.SendPropertyChanging();
					this._CepTelefonu = value;
					this.SendPropertyChanged("CepTelefonu");
					this.OnCepTelefonuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SehirID", DbType="Int NOT NULL")]
		public int SehirID
		{
			get
			{
				return this._SehirID;
			}
			set
			{
				if ((this._SehirID != value))
				{
					if (this._Sehirler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSehirIDChanging(value);
					this.SendPropertyChanging();
					this._SehirID = value;
					this.SendPropertyChanged("SehirID");
					this.OnSehirIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(50)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCKimlikNo", DbType="VarChar(50)")]
		public string TCKimlikNo
		{
			get
			{
				return this._TCKimlikNo;
			}
			set
			{
				if ((this._TCKimlikNo != value))
				{
					this.OnTCKimlikNoChanging(value);
					this.SendPropertyChanging();
					this._TCKimlikNo = value;
					this.SendPropertyChanged("TCKimlikNo");
					this.OnTCKimlikNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteriler_SatisHareketleri", Storage="_SatisHareketleris", ThisKey="MusteriID", OtherKey="MusteriID")]
		public EntitySet<SatisHareketleri> SatisHareketleris
		{
			get
			{
				return this._SatisHareketleris;
			}
			set
			{
				this._SatisHareketleris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sehirler_Musteriler", Storage="_Sehirler", ThisKey="SehirID", OtherKey="SehirID", IsForeignKey=true)]
		public Sehirler Sehirler
		{
			get
			{
				return this._Sehirler.Entity;
			}
			set
			{
				Sehirler previousValue = this._Sehirler.Entity;
				if (((previousValue != value) 
							|| (this._Sehirler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sehirler.Entity = null;
						previousValue.Musterilers.Remove(this);
					}
					this._Sehirler.Entity = value;
					if ((value != null))
					{
						value.Musterilers.Add(this);
						this._SehirID = value.SehirID;
					}
					else
					{
						this._SehirID = default(int);
					}
					this.SendPropertyChanged("Sehirler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SatisHareketleris(SatisHareketleri entity)
		{
			this.SendPropertyChanging();
			entity.Musteriler = this;
		}
		
		private void detach_SatisHareketleris(SatisHareketleri entity)
		{
			this.SendPropertyChanging();
			entity.Musteriler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sehirler")]
	public partial class Sehirler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SehirID;
		
		private string _SehirAdi;
		
		private int _UlkeID;
		
		private string _Aciklama;
		
		private bool _Silindi;
		
		private EntitySet<Havalimanlari> _Havalimanlaris;
		
		private EntitySet<Musteriler> _Musterilers;
		
		private EntityRef<Ulkeler> _Ulkeler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSehirIDChanging(int value);
    partial void OnSehirIDChanged();
    partial void OnSehirAdiChanging(string value);
    partial void OnSehirAdiChanged();
    partial void OnUlkeIDChanging(int value);
    partial void OnUlkeIDChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    #endregion
		
		public Sehirler()
		{
			this._Havalimanlaris = new EntitySet<Havalimanlari>(new Action<Havalimanlari>(this.attach_Havalimanlaris), new Action<Havalimanlari>(this.detach_Havalimanlaris));
			this._Musterilers = new EntitySet<Musteriler>(new Action<Musteriler>(this.attach_Musterilers), new Action<Musteriler>(this.detach_Musterilers));
			this._Ulkeler = default(EntityRef<Ulkeler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SehirID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SehirID
		{
			get
			{
				return this._SehirID;
			}
			set
			{
				if ((this._SehirID != value))
				{
					this.OnSehirIDChanging(value);
					this.SendPropertyChanging();
					this._SehirID = value;
					this.SendPropertyChanged("SehirID");
					this.OnSehirIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SehirAdi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SehirAdi
		{
			get
			{
				return this._SehirAdi;
			}
			set
			{
				if ((this._SehirAdi != value))
				{
					this.OnSehirAdiChanging(value);
					this.SendPropertyChanging();
					this._SehirAdi = value;
					this.SendPropertyChanged("SehirAdi");
					this.OnSehirAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UlkeID", DbType="Int NOT NULL")]
		public int UlkeID
		{
			get
			{
				return this._UlkeID;
			}
			set
			{
				if ((this._UlkeID != value))
				{
					if (this._Ulkeler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUlkeIDChanging(value);
					this.SendPropertyChanging();
					this._UlkeID = value;
					this.SendPropertyChanged("UlkeID");
					this.OnUlkeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(50)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sehirler_Havalimanlari", Storage="_Havalimanlaris", ThisKey="SehirID", OtherKey="SehirID")]
		public EntitySet<Havalimanlari> Havalimanlaris
		{
			get
			{
				return this._Havalimanlaris;
			}
			set
			{
				this._Havalimanlaris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sehirler_Musteriler", Storage="_Musterilers", ThisKey="SehirID", OtherKey="SehirID")]
		public EntitySet<Musteriler> Musterilers
		{
			get
			{
				return this._Musterilers;
			}
			set
			{
				this._Musterilers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ulkeler_Sehirler", Storage="_Ulkeler", ThisKey="UlkeID", OtherKey="UlkeID", IsForeignKey=true)]
		public Ulkeler Ulkeler
		{
			get
			{
				return this._Ulkeler.Entity;
			}
			set
			{
				Ulkeler previousValue = this._Ulkeler.Entity;
				if (((previousValue != value) 
							|| (this._Ulkeler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ulkeler.Entity = null;
						previousValue.Sehirlers.Remove(this);
					}
					this._Ulkeler.Entity = value;
					if ((value != null))
					{
						value.Sehirlers.Add(this);
						this._UlkeID = value.UlkeID;
					}
					else
					{
						this._UlkeID = default(int);
					}
					this.SendPropertyChanged("Ulkeler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Havalimanlaris(Havalimanlari entity)
		{
			this.SendPropertyChanging();
			entity.Sehirler = this;
		}
		
		private void detach_Havalimanlaris(Havalimanlari entity)
		{
			this.SendPropertyChanging();
			entity.Sehirler = null;
		}
		
		private void attach_Musterilers(Musteriler entity)
		{
			this.SendPropertyChanging();
			entity.Sehirler = this;
		}
		
		private void detach_Musterilers(Musteriler entity)
		{
			this.SendPropertyChanging();
			entity.Sehirler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ucaklar")]
	public partial class Ucaklar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UcakID;
		
		private string _UcakAdi;
		
		private int _HavayollariID;
		
		private int _ModelID;
		
		private string _Aciklama;
		
		private bool _Silindi;
		
		private EntitySet<Ucuslar> _Ucuslars;
		
		private EntityRef<Havayollari> _Havayollari;
		
		private EntityRef<Modeller> _Modeller;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUcakIDChanging(int value);
    partial void OnUcakIDChanged();
    partial void OnUcakAdiChanging(string value);
    partial void OnUcakAdiChanged();
    partial void OnHavayollariIDChanging(int value);
    partial void OnHavayollariIDChanged();
    partial void OnModelIDChanging(int value);
    partial void OnModelIDChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    #endregion
		
		public Ucaklar()
		{
			this._Ucuslars = new EntitySet<Ucuslar>(new Action<Ucuslar>(this.attach_Ucuslars), new Action<Ucuslar>(this.detach_Ucuslars));
			this._Havayollari = default(EntityRef<Havayollari>);
			this._Modeller = default(EntityRef<Modeller>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UcakID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UcakID
		{
			get
			{
				return this._UcakID;
			}
			set
			{
				if ((this._UcakID != value))
				{
					this.OnUcakIDChanging(value);
					this.SendPropertyChanging();
					this._UcakID = value;
					this.SendPropertyChanged("UcakID");
					this.OnUcakIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UcakAdi", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string UcakAdi
		{
			get
			{
				return this._UcakAdi;
			}
			set
			{
				if ((this._UcakAdi != value))
				{
					this.OnUcakAdiChanging(value);
					this.SendPropertyChanging();
					this._UcakAdi = value;
					this.SendPropertyChanged("UcakAdi");
					this.OnUcakAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HavayollariID", DbType="Int NOT NULL")]
		public int HavayollariID
		{
			get
			{
				return this._HavayollariID;
			}
			set
			{
				if ((this._HavayollariID != value))
				{
					if (this._Havayollari.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHavayollariIDChanging(value);
					this.SendPropertyChanging();
					this._HavayollariID = value;
					this.SendPropertyChanged("HavayollariID");
					this.OnHavayollariIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelID", DbType="Int NOT NULL")]
		public int ModelID
		{
			get
			{
				return this._ModelID;
			}
			set
			{
				if ((this._ModelID != value))
				{
					if (this._Modeller.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnModelIDChanging(value);
					this.SendPropertyChanging();
					this._ModelID = value;
					this.SendPropertyChanged("ModelID");
					this.OnModelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ucaklar_Ucuslar", Storage="_Ucuslars", ThisKey="UcakID", OtherKey="UcakID")]
		public EntitySet<Ucuslar> Ucuslars
		{
			get
			{
				return this._Ucuslars;
			}
			set
			{
				this._Ucuslars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Havayollari_Ucaklar", Storage="_Havayollari", ThisKey="HavayollariID", OtherKey="HavayoluID", IsForeignKey=true)]
		public Havayollari Havayollari
		{
			get
			{
				return this._Havayollari.Entity;
			}
			set
			{
				Havayollari previousValue = this._Havayollari.Entity;
				if (((previousValue != value) 
							|| (this._Havayollari.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Havayollari.Entity = null;
						previousValue.Ucaklars.Remove(this);
					}
					this._Havayollari.Entity = value;
					if ((value != null))
					{
						value.Ucaklars.Add(this);
						this._HavayollariID = value.HavayoluID;
					}
					else
					{
						this._HavayollariID = default(int);
					}
					this.SendPropertyChanged("Havayollari");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Modeller_Ucaklar", Storage="_Modeller", ThisKey="ModelID", OtherKey="ModelID", IsForeignKey=true)]
		public Modeller Modeller
		{
			get
			{
				return this._Modeller.Entity;
			}
			set
			{
				Modeller previousValue = this._Modeller.Entity;
				if (((previousValue != value) 
							|| (this._Modeller.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Modeller.Entity = null;
						previousValue.Ucaklars.Remove(this);
					}
					this._Modeller.Entity = value;
					if ((value != null))
					{
						value.Ucaklars.Add(this);
						this._ModelID = value.ModelID;
					}
					else
					{
						this._ModelID = default(int);
					}
					this.SendPropertyChanged("Modeller");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ucuslars(Ucuslar entity)
		{
			this.SendPropertyChanging();
			entity.Ucaklar = this;
		}
		
		private void detach_Ucuslars(Ucuslar entity)
		{
			this.SendPropertyChanging();
			entity.Ucaklar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ucuslar")]
	public partial class Ucuslar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UcusID;
		
		private string _UcusAdi;
		
		private int _UcakID;
		
		private int _KalkisYeriID;
		
		private int _InisYeriID;
		
		private System.DateTime _UcusTarihi;
		
		private int _Sure;
		
		private int _FirstClassBosKoltuk;
		
		private int _BusinessClassBosKoltuk;
		
		private int _EkonimikBosKoltuk;
		
		private decimal _EkonomikFiyat;
		
		private decimal _FirstClassFiyat;
		
		private decimal _BusinessClassFiyat;
		
		private bool _Silindi;
		
		private decimal _EkstraBagajFiyat;
		
		private string _UcusSaati;
		
		private EntitySet<SatisHareketleri> _SatisHareketleris;
		
		private EntityRef<Havalimanlari> _Havalimanlari;
		
		private EntityRef<Havalimanlari> _Havalimanlari1;
		
		private EntityRef<Havalimanlari> _Havalimanlari2;
		
		private EntityRef<Ucaklar> _Ucaklar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUcusIDChanging(int value);
    partial void OnUcusIDChanged();
    partial void OnUcusAdiChanging(string value);
    partial void OnUcusAdiChanged();
    partial void OnUcakIDChanging(int value);
    partial void OnUcakIDChanged();
    partial void OnKalkisYeriIDChanging(int value);
    partial void OnKalkisYeriIDChanged();
    partial void OnInisYeriIDChanging(int value);
    partial void OnInisYeriIDChanged();
    partial void OnUcusTarihiChanging(System.DateTime value);
    partial void OnUcusTarihiChanged();
    partial void OnSureChanging(int value);
    partial void OnSureChanged();
    partial void OnFirstClassBosKoltukChanging(int value);
    partial void OnFirstClassBosKoltukChanged();
    partial void OnBusinessClassBosKoltukChanging(int value);
    partial void OnBusinessClassBosKoltukChanged();
    partial void OnEkonimikBosKoltukChanging(int value);
    partial void OnEkonimikBosKoltukChanged();
    partial void OnEkonomikFiyatChanging(decimal value);
    partial void OnEkonomikFiyatChanged();
    partial void OnFirstClassFiyatChanging(decimal value);
    partial void OnFirstClassFiyatChanged();
    partial void OnBusinessClassFiyatChanging(decimal value);
    partial void OnBusinessClassFiyatChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    partial void OnEkstraBagajFiyatChanging(decimal value);
    partial void OnEkstraBagajFiyatChanged();
    partial void OnUcusSaatiChanging(string value);
    partial void OnUcusSaatiChanged();
    #endregion
		
		public Ucuslar()
		{
			this._SatisHareketleris = new EntitySet<SatisHareketleri>(new Action<SatisHareketleri>(this.attach_SatisHareketleris), new Action<SatisHareketleri>(this.detach_SatisHareketleris));
			this._Havalimanlari = default(EntityRef<Havalimanlari>);
			this._Havalimanlari1 = default(EntityRef<Havalimanlari>);
			this._Havalimanlari2 = default(EntityRef<Havalimanlari>);
			this._Ucaklar = default(EntityRef<Ucaklar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UcusID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UcusID
		{
			get
			{
				return this._UcusID;
			}
			set
			{
				if ((this._UcusID != value))
				{
					this.OnUcusIDChanging(value);
					this.SendPropertyChanging();
					this._UcusID = value;
					this.SendPropertyChanged("UcusID");
					this.OnUcusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UcusAdi", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string UcusAdi
		{
			get
			{
				return this._UcusAdi;
			}
			set
			{
				if ((this._UcusAdi != value))
				{
					this.OnUcusAdiChanging(value);
					this.SendPropertyChanging();
					this._UcusAdi = value;
					this.SendPropertyChanged("UcusAdi");
					this.OnUcusAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UcakID", DbType="Int NOT NULL")]
		public int UcakID
		{
			get
			{
				return this._UcakID;
			}
			set
			{
				if ((this._UcakID != value))
				{
					if (this._Ucaklar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUcakIDChanging(value);
					this.SendPropertyChanging();
					this._UcakID = value;
					this.SendPropertyChanged("UcakID");
					this.OnUcakIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KalkisYeriID", DbType="Int NOT NULL")]
		public int KalkisYeriID
		{
			get
			{
				return this._KalkisYeriID;
			}
			set
			{
				if ((this._KalkisYeriID != value))
				{
					if ((this._Havalimanlari.HasLoadedOrAssignedValue || this._Havalimanlari2.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKalkisYeriIDChanging(value);
					this.SendPropertyChanging();
					this._KalkisYeriID = value;
					this.SendPropertyChanged("KalkisYeriID");
					this.OnKalkisYeriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InisYeriID", DbType="Int NOT NULL")]
		public int InisYeriID
		{
			get
			{
				return this._InisYeriID;
			}
			set
			{
				if ((this._InisYeriID != value))
				{
					if (this._Havalimanlari1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnInisYeriIDChanging(value);
					this.SendPropertyChanging();
					this._InisYeriID = value;
					this.SendPropertyChanged("InisYeriID");
					this.OnInisYeriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UcusTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime UcusTarihi
		{
			get
			{
				return this._UcusTarihi;
			}
			set
			{
				if ((this._UcusTarihi != value))
				{
					this.OnUcusTarihiChanging(value);
					this.SendPropertyChanging();
					this._UcusTarihi = value;
					this.SendPropertyChanged("UcusTarihi");
					this.OnUcusTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Int NOT NULL")]
		public int Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this.OnSureChanging(value);
					this.SendPropertyChanging();
					this._Sure = value;
					this.SendPropertyChanged("Sure");
					this.OnSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstClassBosKoltuk", DbType="Int NOT NULL")]
		public int FirstClassBosKoltuk
		{
			get
			{
				return this._FirstClassBosKoltuk;
			}
			set
			{
				if ((this._FirstClassBosKoltuk != value))
				{
					this.OnFirstClassBosKoltukChanging(value);
					this.SendPropertyChanging();
					this._FirstClassBosKoltuk = value;
					this.SendPropertyChanged("FirstClassBosKoltuk");
					this.OnFirstClassBosKoltukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessClassBosKoltuk", DbType="Int NOT NULL")]
		public int BusinessClassBosKoltuk
		{
			get
			{
				return this._BusinessClassBosKoltuk;
			}
			set
			{
				if ((this._BusinessClassBosKoltuk != value))
				{
					this.OnBusinessClassBosKoltukChanging(value);
					this.SendPropertyChanging();
					this._BusinessClassBosKoltuk = value;
					this.SendPropertyChanged("BusinessClassBosKoltuk");
					this.OnBusinessClassBosKoltukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EkonimikBosKoltuk", DbType="Int NOT NULL")]
		public int EkonimikBosKoltuk
		{
			get
			{
				return this._EkonimikBosKoltuk;
			}
			set
			{
				if ((this._EkonimikBosKoltuk != value))
				{
					this.OnEkonimikBosKoltukChanging(value);
					this.SendPropertyChanging();
					this._EkonimikBosKoltuk = value;
					this.SendPropertyChanged("EkonimikBosKoltuk");
					this.OnEkonimikBosKoltukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EkonomikFiyat", DbType="Money NOT NULL")]
		public decimal EkonomikFiyat
		{
			get
			{
				return this._EkonomikFiyat;
			}
			set
			{
				if ((this._EkonomikFiyat != value))
				{
					this.OnEkonomikFiyatChanging(value);
					this.SendPropertyChanging();
					this._EkonomikFiyat = value;
					this.SendPropertyChanged("EkonomikFiyat");
					this.OnEkonomikFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstClassFiyat", DbType="Money NOT NULL")]
		public decimal FirstClassFiyat
		{
			get
			{
				return this._FirstClassFiyat;
			}
			set
			{
				if ((this._FirstClassFiyat != value))
				{
					this.OnFirstClassFiyatChanging(value);
					this.SendPropertyChanging();
					this._FirstClassFiyat = value;
					this.SendPropertyChanged("FirstClassFiyat");
					this.OnFirstClassFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessClassFiyat", DbType="Money NOT NULL")]
		public decimal BusinessClassFiyat
		{
			get
			{
				return this._BusinessClassFiyat;
			}
			set
			{
				if ((this._BusinessClassFiyat != value))
				{
					this.OnBusinessClassFiyatChanging(value);
					this.SendPropertyChanging();
					this._BusinessClassFiyat = value;
					this.SendPropertyChanged("BusinessClassFiyat");
					this.OnBusinessClassFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EkstraBagajFiyat", DbType="Money NOT NULL")]
		public decimal EkstraBagajFiyat
		{
			get
			{
				return this._EkstraBagajFiyat;
			}
			set
			{
				if ((this._EkstraBagajFiyat != value))
				{
					this.OnEkstraBagajFiyatChanging(value);
					this.SendPropertyChanging();
					this._EkstraBagajFiyat = value;
					this.SendPropertyChanged("EkstraBagajFiyat");
					this.OnEkstraBagajFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UcusSaati", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string UcusSaati
		{
			get
			{
				return this._UcusSaati;
			}
			set
			{
				if ((this._UcusSaati != value))
				{
					this.OnUcusSaatiChanging(value);
					this.SendPropertyChanging();
					this._UcusSaati = value;
					this.SendPropertyChanged("UcusSaati");
					this.OnUcusSaatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ucuslar_SatisHareketleri", Storage="_SatisHareketleris", ThisKey="UcusID", OtherKey="UcusID")]
		public EntitySet<SatisHareketleri> SatisHareketleris
		{
			get
			{
				return this._SatisHareketleris;
			}
			set
			{
				this._SatisHareketleris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Havalimanlari_Ucuslar", Storage="_Havalimanlari", ThisKey="KalkisYeriID", OtherKey="HavalimaniID", IsForeignKey=true)]
		public Havalimanlari Havalimanlari
		{
			get
			{
				return this._Havalimanlari.Entity;
			}
			set
			{
				Havalimanlari previousValue = this._Havalimanlari.Entity;
				if (((previousValue != value) 
							|| (this._Havalimanlari.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Havalimanlari.Entity = null;
						previousValue.Ucuslars.Remove(this);
					}
					this._Havalimanlari.Entity = value;
					if ((value != null))
					{
						value.Ucuslars.Add(this);
						this._KalkisYeriID = value.HavalimaniID;
					}
					else
					{
						this._KalkisYeriID = default(int);
					}
					this.SendPropertyChanged("Havalimanlari");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Havalimanlari_Ucuslar1", Storage="_Havalimanlari1", ThisKey="InisYeriID", OtherKey="HavalimaniID", IsForeignKey=true)]
		public Havalimanlari Havalimanlari1
		{
			get
			{
				return this._Havalimanlari1.Entity;
			}
			set
			{
				Havalimanlari previousValue = this._Havalimanlari1.Entity;
				if (((previousValue != value) 
							|| (this._Havalimanlari1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Havalimanlari1.Entity = null;
						previousValue.Ucuslars1.Remove(this);
					}
					this._Havalimanlari1.Entity = value;
					if ((value != null))
					{
						value.Ucuslars1.Add(this);
						this._InisYeriID = value.HavalimaniID;
					}
					else
					{
						this._InisYeriID = default(int);
					}
					this.SendPropertyChanged("Havalimanlari1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Havalimanlari_Ucuslar2", Storage="_Havalimanlari2", ThisKey="KalkisYeriID", OtherKey="HavalimaniID", IsForeignKey=true)]
		public Havalimanlari Havalimanlari2
		{
			get
			{
				return this._Havalimanlari2.Entity;
			}
			set
			{
				Havalimanlari previousValue = this._Havalimanlari2.Entity;
				if (((previousValue != value) 
							|| (this._Havalimanlari2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Havalimanlari2.Entity = null;
						previousValue.Ucuslars2.Remove(this);
					}
					this._Havalimanlari2.Entity = value;
					if ((value != null))
					{
						value.Ucuslars2.Add(this);
						this._KalkisYeriID = value.HavalimaniID;
					}
					else
					{
						this._KalkisYeriID = default(int);
					}
					this.SendPropertyChanged("Havalimanlari2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ucaklar_Ucuslar", Storage="_Ucaklar", ThisKey="UcakID", OtherKey="UcakID", IsForeignKey=true)]
		public Ucaklar Ucaklar
		{
			get
			{
				return this._Ucaklar.Entity;
			}
			set
			{
				Ucaklar previousValue = this._Ucaklar.Entity;
				if (((previousValue != value) 
							|| (this._Ucaklar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ucaklar.Entity = null;
						previousValue.Ucuslars.Remove(this);
					}
					this._Ucaklar.Entity = value;
					if ((value != null))
					{
						value.Ucuslars.Add(this);
						this._UcakID = value.UcakID;
					}
					else
					{
						this._UcakID = default(int);
					}
					this.SendPropertyChanged("Ucaklar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SatisHareketleris(SatisHareketleri entity)
		{
			this.SendPropertyChanging();
			entity.Ucuslar = this;
		}
		
		private void detach_SatisHareketleris(SatisHareketleri entity)
		{
			this.SendPropertyChanging();
			entity.Ucuslar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ulkeler")]
	public partial class Ulkeler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UlkeID;
		
		private string _UlkeAdi;
		
		private string _Aciklama;
		
		private string _UlkeTelCod;
		
		private bool _Silindi;
		
		private EntitySet<Havayollari> _Havayollaris;
		
		private EntitySet<Sehirler> _Sehirlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUlkeIDChanging(int value);
    partial void OnUlkeIDChanged();
    partial void OnUlkeAdiChanging(string value);
    partial void OnUlkeAdiChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnUlkeTelCodChanging(string value);
    partial void OnUlkeTelCodChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    #endregion
		
		public Ulkeler()
		{
			this._Havayollaris = new EntitySet<Havayollari>(new Action<Havayollari>(this.attach_Havayollaris), new Action<Havayollari>(this.detach_Havayollaris));
			this._Sehirlers = new EntitySet<Sehirler>(new Action<Sehirler>(this.attach_Sehirlers), new Action<Sehirler>(this.detach_Sehirlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UlkeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UlkeID
		{
			get
			{
				return this._UlkeID;
			}
			set
			{
				if ((this._UlkeID != value))
				{
					this.OnUlkeIDChanging(value);
					this.SendPropertyChanging();
					this._UlkeID = value;
					this.SendPropertyChanged("UlkeID");
					this.OnUlkeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UlkeAdi", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string UlkeAdi
		{
			get
			{
				return this._UlkeAdi;
			}
			set
			{
				if ((this._UlkeAdi != value))
				{
					this.OnUlkeAdiChanging(value);
					this.SendPropertyChanging();
					this._UlkeAdi = value;
					this.SendPropertyChanged("UlkeAdi");
					this.OnUlkeAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(150)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UlkeTelCod", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string UlkeTelCod
		{
			get
			{
				return this._UlkeTelCod;
			}
			set
			{
				if ((this._UlkeTelCod != value))
				{
					this.OnUlkeTelCodChanging(value);
					this.SendPropertyChanging();
					this._UlkeTelCod = value;
					this.SendPropertyChanged("UlkeTelCod");
					this.OnUlkeTelCodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ulkeler_Havayollari", Storage="_Havayollaris", ThisKey="UlkeID", OtherKey="UlkeID")]
		public EntitySet<Havayollari> Havayollaris
		{
			get
			{
				return this._Havayollaris;
			}
			set
			{
				this._Havayollaris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ulkeler_Sehirler", Storage="_Sehirlers", ThisKey="UlkeID", OtherKey="UlkeID")]
		public EntitySet<Sehirler> Sehirlers
		{
			get
			{
				return this._Sehirlers;
			}
			set
			{
				this._Sehirlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Havayollaris(Havayollari entity)
		{
			this.SendPropertyChanging();
			entity.Ulkeler = this;
		}
		
		private void detach_Havayollaris(Havayollari entity)
		{
			this.SendPropertyChanging();
			entity.Ulkeler = null;
		}
		
		private void attach_Sehirlers(Sehirler entity)
		{
			this.SendPropertyChanging();
			entity.Ulkeler = this;
		}
		
		private void detach_Sehirlers(Sehirler entity)
		{
			this.SendPropertyChanging();
			entity.Ulkeler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Modeller")]
	public partial class Modeller : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ModelID;
		
		private string _ModelAdi;
		
		private int _EkoKoltukAdeti;
		
		private int _BusinessKoltukAdeti;
		
		private int _FirstKoltukAdeti;
		
		private string _Aciklama;
		
		private bool _Silindi;
		
		private EntitySet<Ucaklar> _Ucaklars;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnModelIDChanging(int value);
    partial void OnModelIDChanged();
    partial void OnModelAdiChanging(string value);
    partial void OnModelAdiChanged();
    partial void OnEkoKoltukAdetiChanging(int value);
    partial void OnEkoKoltukAdetiChanged();
    partial void OnBusinessKoltukAdetiChanging(int value);
    partial void OnBusinessKoltukAdetiChanged();
    partial void OnFirstKoltukAdetiChanging(int value);
    partial void OnFirstKoltukAdetiChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    #endregion
		
		public Modeller()
		{
			this._Ucaklars = new EntitySet<Ucaklar>(new Action<Ucaklar>(this.attach_Ucaklars), new Action<Ucaklar>(this.detach_Ucaklars));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ModelID
		{
			get
			{
				return this._ModelID;
			}
			set
			{
				if ((this._ModelID != value))
				{
					this.OnModelIDChanging(value);
					this.SendPropertyChanging();
					this._ModelID = value;
					this.SendPropertyChanged("ModelID");
					this.OnModelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelAdi", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ModelAdi
		{
			get
			{
				return this._ModelAdi;
			}
			set
			{
				if ((this._ModelAdi != value))
				{
					this.OnModelAdiChanging(value);
					this.SendPropertyChanging();
					this._ModelAdi = value;
					this.SendPropertyChanged("ModelAdi");
					this.OnModelAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EkoKoltukAdeti", DbType="Int NOT NULL")]
		public int EkoKoltukAdeti
		{
			get
			{
				return this._EkoKoltukAdeti;
			}
			set
			{
				if ((this._EkoKoltukAdeti != value))
				{
					this.OnEkoKoltukAdetiChanging(value);
					this.SendPropertyChanging();
					this._EkoKoltukAdeti = value;
					this.SendPropertyChanged("EkoKoltukAdeti");
					this.OnEkoKoltukAdetiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessKoltukAdeti", DbType="Int NOT NULL")]
		public int BusinessKoltukAdeti
		{
			get
			{
				return this._BusinessKoltukAdeti;
			}
			set
			{
				if ((this._BusinessKoltukAdeti != value))
				{
					this.OnBusinessKoltukAdetiChanging(value);
					this.SendPropertyChanging();
					this._BusinessKoltukAdeti = value;
					this.SendPropertyChanged("BusinessKoltukAdeti");
					this.OnBusinessKoltukAdetiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstKoltukAdeti", DbType="Int NOT NULL")]
		public int FirstKoltukAdeti
		{
			get
			{
				return this._FirstKoltukAdeti;
			}
			set
			{
				if ((this._FirstKoltukAdeti != value))
				{
					this.OnFirstKoltukAdetiChanging(value);
					this.SendPropertyChanging();
					this._FirstKoltukAdeti = value;
					this.SendPropertyChanged("FirstKoltukAdeti");
					this.OnFirstKoltukAdetiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(50)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Modeller_Ucaklar", Storage="_Ucaklars", ThisKey="ModelID", OtherKey="ModelID")]
		public EntitySet<Ucaklar> Ucaklars
		{
			get
			{
				return this._Ucaklars;
			}
			set
			{
				this._Ucaklars.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ucaklars(Ucaklar entity)
		{
			this.SendPropertyChanging();
			entity.Modeller = this;
		}
		
		private void detach_Ucaklars(Ucaklar entity)
		{
			this.SendPropertyChanging();
			entity.Modeller = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SatisHareketleri")]
	public partial class SatisHareketleri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SatisID;
		
		private string _PNRCode;
		
		private int _MusteriID;
		
		private System.DateTime _Tarih;
		
		private int _UcusID;
		
		private int _Adet;
		
		private string _Status;
		
		private decimal _BirimFiyat;
		
		private System.Nullable<decimal> _Tutar;
		
		private string _TekilKod;
		
		private bool _Silindi;
		
		private string _Aciklama;
		
		private int _EkstraBagajKilosu;
		
		private decimal _ToplamTutar;
		
		private EntityRef<Musteriler> _Musteriler;
		
		private EntityRef<Ucuslar> _Ucuslar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSatisIDChanging(int value);
    partial void OnSatisIDChanged();
    partial void OnPNRCodeChanging(string value);
    partial void OnPNRCodeChanged();
    partial void OnMusteriIDChanging(int value);
    partial void OnMusteriIDChanged();
    partial void OnTarihChanging(System.DateTime value);
    partial void OnTarihChanged();
    partial void OnUcusIDChanging(int value);
    partial void OnUcusIDChanged();
    partial void OnAdetChanging(int value);
    partial void OnAdetChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnBirimFiyatChanging(decimal value);
    partial void OnBirimFiyatChanged();
    partial void OnTutarChanging(System.Nullable<decimal> value);
    partial void OnTutarChanged();
    partial void OnTekilKodChanging(string value);
    partial void OnTekilKodChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnEkstraBagajKilosuChanging(int value);
    partial void OnEkstraBagajKilosuChanged();
    partial void OnToplamTutarChanging(decimal value);
    partial void OnToplamTutarChanged();
    #endregion
		
		public SatisHareketleri()
		{
			this._Musteriler = default(EntityRef<Musteriler>);
			this._Ucuslar = default(EntityRef<Ucuslar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SatisID
		{
			get
			{
				return this._SatisID;
			}
			set
			{
				if ((this._SatisID != value))
				{
					this.OnSatisIDChanging(value);
					this.SendPropertyChanging();
					this._SatisID = value;
					this.SendPropertyChanged("SatisID");
					this.OnSatisIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNRCode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PNRCode
		{
			get
			{
				return this._PNRCode;
			}
			set
			{
				if ((this._PNRCode != value))
				{
					this.OnPNRCodeChanging(value);
					this.SendPropertyChanging();
					this._PNRCode = value;
					this.SendPropertyChanged("PNRCode");
					this.OnPNRCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriID", DbType="Int NOT NULL")]
		public int MusteriID
		{
			get
			{
				return this._MusteriID;
			}
			set
			{
				if ((this._MusteriID != value))
				{
					if (this._Musteriler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMusteriIDChanging(value);
					this.SendPropertyChanging();
					this._MusteriID = value;
					this.SendPropertyChanged("MusteriID");
					this.OnMusteriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime NOT NULL")]
		public System.DateTime Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UcusID", DbType="Int NOT NULL")]
		public int UcusID
		{
			get
			{
				return this._UcusID;
			}
			set
			{
				if ((this._UcusID != value))
				{
					if (this._Ucuslar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUcusIDChanging(value);
					this.SendPropertyChanging();
					this._UcusID = value;
					this.SendPropertyChanged("UcusID");
					this.OnUcusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="Int NOT NULL")]
		public int Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this.OnAdetChanging(value);
					this.SendPropertyChanging();
					this._Adet = value;
					this.SendPropertyChanged("Adet");
					this.OnAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirimFiyat", DbType="Money NOT NULL")]
		public decimal BirimFiyat
		{
			get
			{
				return this._BirimFiyat;
			}
			set
			{
				if ((this._BirimFiyat != value))
				{
					this.OnBirimFiyatChanging(value);
					this.SendPropertyChanging();
					this._BirimFiyat = value;
					this.SendPropertyChanged("BirimFiyat");
					this.OnBirimFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", AutoSync=AutoSync.Always, DbType="Money", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this.OnTutarChanging(value);
					this.SendPropertyChanging();
					this._Tutar = value;
					this.SendPropertyChanged("Tutar");
					this.OnTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TekilKod", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TekilKod
		{
			get
			{
				return this._TekilKod;
			}
			set
			{
				if ((this._TekilKod != value))
				{
					this.OnTekilKodChanging(value);
					this.SendPropertyChanging();
					this._TekilKod = value;
					this.SendPropertyChanged("TekilKod");
					this.OnTekilKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(50)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EkstraBagajKilosu", DbType="Int NOT NULL")]
		public int EkstraBagajKilosu
		{
			get
			{
				return this._EkstraBagajKilosu;
			}
			set
			{
				if ((this._EkstraBagajKilosu != value))
				{
					this.OnEkstraBagajKilosuChanging(value);
					this.SendPropertyChanging();
					this._EkstraBagajKilosu = value;
					this.SendPropertyChanged("EkstraBagajKilosu");
					this.OnEkstraBagajKilosuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToplamTutar", DbType="Money NOT NULL")]
		public decimal ToplamTutar
		{
			get
			{
				return this._ToplamTutar;
			}
			set
			{
				if ((this._ToplamTutar != value))
				{
					this.OnToplamTutarChanging(value);
					this.SendPropertyChanging();
					this._ToplamTutar = value;
					this.SendPropertyChanged("ToplamTutar");
					this.OnToplamTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteriler_SatisHareketleri", Storage="_Musteriler", ThisKey="MusteriID", OtherKey="MusteriID", IsForeignKey=true)]
		public Musteriler Musteriler
		{
			get
			{
				return this._Musteriler.Entity;
			}
			set
			{
				Musteriler previousValue = this._Musteriler.Entity;
				if (((previousValue != value) 
							|| (this._Musteriler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Musteriler.Entity = null;
						previousValue.SatisHareketleris.Remove(this);
					}
					this._Musteriler.Entity = value;
					if ((value != null))
					{
						value.SatisHareketleris.Add(this);
						this._MusteriID = value.MusteriID;
					}
					else
					{
						this._MusteriID = default(int);
					}
					this.SendPropertyChanged("Musteriler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ucuslar_SatisHareketleri", Storage="_Ucuslar", ThisKey="UcusID", OtherKey="UcusID", IsForeignKey=true)]
		public Ucuslar Ucuslar
		{
			get
			{
				return this._Ucuslar.Entity;
			}
			set
			{
				Ucuslar previousValue = this._Ucuslar.Entity;
				if (((previousValue != value) 
							|| (this._Ucuslar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ucuslar.Entity = null;
						previousValue.SatisHareketleris.Remove(this);
					}
					this._Ucuslar.Entity = value;
					if ((value != null))
					{
						value.SatisHareketleris.Add(this);
						this._UcusID = value.UcusID;
					}
					else
					{
						this._UcusID = default(int);
					}
					this.SendPropertyChanged("Ucuslar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
